// generated by jsonutils.com
// edited names, added comments and code style aligned

using System.Collections.Generic;
using Newtonsoft.Json;

namespace IucnRedList.Model
{
  /// <summary>
  /// Represents IUCN Red List API V3 response for Regional measures service methods
  /// </summary>
  /// <see cref="http://apiv3.iucnredlist.org/api/v3/docs#measures"/>
  public class ConservationMeasuresResponse
  {
    [JsonProperty("id")]
    public string Id { get; set; }

    [JsonProperty("region_identifier")]
    public string RegionIdentifier { get; set; }

    [JsonProperty("result")]
    public IList<ConservationMeasure> Result { get; set; }
  }
}
