// generated by jsonutils.com
// edited names, added comments and code style aligned

using System.Collections.Generic;
using Newtonsoft.Json;

namespace IucnRedList.Model
{
  public class ConservationMeasuresResponse
  {
    [JsonProperty("id")]
    public string Id { get; set; }

    [JsonProperty("region_identifier")]
    public string RegionIdentifier { get; set; }

    [JsonProperty("result")]
    public IList<ConservationMeasure> Result { get; set; }
  }
}
