// generated by jsonutils.com
// edited names, added comments and code style aligned

using Newtonsoft.Json;

namespace IucnRedList.Model
{
  /// <summary>
  /// Represents IUCN Red List API V3 Conservation Measure result item
  /// </summary>
  public class ConservationMeasure
  {
    [JsonProperty("code")]
    public string Code { get; set; }

    [JsonProperty("title")]
    public string Title { get; set; }
  }
}
